compatibility_date = "2025-12-25"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"
name = "fade"
routes = [
  { pattern = "fade.shikanime.studio", custom_domain = true, zone_name = "shikanime.studio" },
]

[observability]
enabled = true
