[project]
name = "websites"
revision = "1.0"

[profiles.default]
GOOGLE_AUTHORIZED_REDIRECT_BASE_URI = { description = "Google OAuth redirect base URI used for authentication", required = true }
GOOGLE_CLIENT_ID = { description = "Google OAuth client ID used for authentication", required = true }
GOOGLE_CLIENT_SECRET = { description = "Google OAuth client secret used for authentication", required = true }
