compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"
name = "www"
routes = [{ pattern = "shikanime.studio", custom_domain = true }]

[[kv_namespaces]]
binding = "KV_BINDING"
preview_id = "2cfe106fa7b546b39e9bace24729e358"

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
