compatibility_date = "2025-12-25"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"
name = "links"
routes = [
  { pattern = "links.shikanime.studio", custom_domain = true, zone_name = "shikanime.studio" },
]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
