name = "links"
compatibility_date = "2025-01-27"
routes = [{ pattern = "links.shikanime.studio", custom_domain = true }]

[[d1_databases]]
binding = "DB"
database_name = "links"
database_id = "0c17e9e3-5b64-49fc-8daa-ceef63c882b5"
